language: node_js
node_js:
  - 12
  - 14
cache: npm
notifications:
  email: false
before_script:
  - npm run lint
after_success:
  - npm install -g codecov
  - codecov
branches:
  except:
    - '/^v\d+\.\d+\.\d+$/'
jobs:
  include:
    - stage: deploy
      if: branch == master && !fork
      node_js: 'node'
      script:
        - npm install -g semantic-release
        - semantic-release